### ISSUE TITLE
添加繁化姬插件后无法加载LiteLoader

### ISSUE THREAD

**Issue by GashByte** [qianxu2001/LiteLoaderQQNT-Plugin-Fanhuaji#1]
如题

![%7B239377E2-586D-498f-B683-FCF24777B4DD%7D](https://github.com/qianxuu/LiteLoaderQQNT-Plugin-Fanhuaji/assets/120739043/2620353e-3d0c-4ff5-a16e-087e04c5fa39)
![QQ截图20230716193953](https://github.com/qianxuu/LiteLoaderQQNT-Plugin-Fanhuaji/assets/120739043/ea46e224-cd29-49c2-952f-33ad35650dd6)

**Comment by qianxuu** [comment]
因为插件用了新的 `LiteLoader` API，release 版的本体不支持，将插件切换到 `old-api` 分支应该就好了

**Comment by GashByte** [comment]
多谢 已经恢复正常了
