### ISSUE TITLE
无法上架插件市场

### ISSUE THREAD

**Issue by mo-jinran** [qianxu2001/LiteLoaderQQNT-Plugin-Fanhuaji#2]
manifest.json文件repository的repo字段写错了
插件市场会无法下载对应插件与打开详情
应该写成`qianxuu/LiteLoaderQQNT-Plugin-Fanhuaji`

**Comment by qianxuu** [comment]
> manifest.json文件repository的repo字段写错了 插件市场会无法下载对应插件与打开详情 应该写成`qianxuu/LiteLoaderQQNT-Plugin-Fanhuaji`

已修复
